import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex justify-between px-12 pt-6">
          <h6>LoGo</h6>
          <ul className="flex gap-4">
            <li>About</li>
            <li>Service</li>
            <li>Contact</li>
            <li>Support</li>
          </ul>
        </nav>
        <div className="h-screen">{children}</div>
        <footer>All Right reserved by Arif telecom</footer>
      </body>
    </html>
  );
}
